Ensure executable dependencies are present
Because:

* The check expects a number of executables to be present on the PATH.
* If they're not available then the check may not behave correctly,
  therefore it should check for their presence and exit with an UNKNOWN
  if any are missing.

diff --git a/check_clamav b/check_clamav
--- a/check_clamav
+++ b/check_clamav
@@ -85,6 +85,14 @@ done
 # Showtime.
 #
 
+# ensure we have executable dependencies
+for dependency in cut grep rev sed; do
+  if ! hash $dependency >/dev/null 2>&1; then
+    echo "UNKNOWN: Missing dependency: ${dependency}"
+    exit $UNKNOWN
+  fi
+done
+
 # ensure we have a LOGFILE_PATH
 if [ -z "$LOGFILE_PATH" ]; then
   echo 'UNKNOWN: --logfile/-l not set'
