Add -e/--expiry arg for setting expiry threshold
Because:

* The default threshold of 48 hours is probably suitable for most cases,
  but not all.

diff --git a/check_clamav b/check_clamav
--- a/check_clamav
+++ b/check_clamav
@@ -44,17 +44,21 @@ help() {
   Examples:
     ./check_clamav -l /tmp/clamav.log
 
+    ./check_clamav -l /tmp/clamav.log -e '1 hour'
+
     ./check_clamav -l /tmp/clamav.log -c 10
 
     ./check_clamav -l /tmp/clamav.log -c 10 -w 5
 
   Options:
     -l, --logfile <path>        path to clamscan logfile
+    -e, --expiry <duration>     expiry threshold for logfile
     -w, --warning <number>      number of infected files treat as WARNING
     -c, --critical <number>     number of infected files to treat as CRITICAL
     -V, --version               output version
     -h, --help                  output help information
 
+  -e/--expiry should be a human readable duration, e.g. '1 hour', or '7 days'.
   -c/--critical takes priority over -w/--warning.
 
   For more information, see https://github.com/tommarshall/nagios-check-clamav
@@ -70,6 +74,7 @@ while test $# -ne 0; do
   ARG=$1; shift
   case $ARG in
     -l|--logfile) LOGFILE_PATH=$1; shift ;;
+    -e|--expiry) EXPIRY_THRESHOLD=$1; shift ;;
     -w|--warning) WARNING_THRESHOLD=$1; shift ;;
     -c|--critical) CRITICAL_THRESHOLD=$1; shift ;;
     -V|--version) version; exit ;;
@@ -150,11 +155,16 @@ if [ -z "$INFECTED_FILES_COUNT" ]; then
   exit $UNKNOWN
 fi
 
+# ensure the expiry argument is valid
+if ! THRESHOLD_DATE="$(date --date="-$EXPIRY_THRESHOLD" +'%s' 2>/dev/null)"; then
+  echo "UNKNOWN: Invalid expiry specified: ${EXPIRY_THRESHOLD}"
+  exit $UNKNOWN
+fi
+
 # ensure the logfile has not expired
 LOGFILE_LAST_MODIFIED_DATE="$(stat --format='%Y' $LOGFILE_PATH)"
-THRESHOLD_DATE="$(date --date="-$EXPIRY_THRESHOLD" +'%s')"
 if [ "$LOGFILE_LAST_MODIFIED_DATE" -lt "$THRESHOLD_DATE" ]; then
-  echo "UNKNOWN: Logfile has expired beyond threshold: ${EXPIRY_THRESHOLD}"
+  echo "UNKNOWN: Logfile has expired, more than ${EXPIRY_THRESHOLD} old"
   exit $UNKNOWN
 fi
 
